
FROM centos:7.2.1511

ENV SUPERVISOR_VERSION=4.0.2

RUN \
	rpm --rebuilddb && yum clean all; \
	yum install -y epel-release; \
	yum update -y; \
	yum install -y \
	iproute \
	python-setuptools \
	hostname \
	inotify-tools \
	yum-utils \
	which \
	jq \
	rsync \
	telnet \
	htop \
	atop \
	iotop \
	mtr \
	vim && \
	yum clean all && rm -rf /tmp/yum*; \
	easy_install pip; \
	pip install supervisor==${SUPERVISOR_VERSION}

  
COPY etc/startup.sh /root/startup.sh
RUN chmod +x /root/startup.sh

ENTRYPOINT ["/root/startup.sh"]
CMD ["/usr/bin/supervisord", "--configuration=/etc/supervisord.conf"]